# Generated by Django 2.2.6 on 2020-01-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind_game', '0002_remove_guess_guess_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=5)),
                ('current_guess', models.IntegerField()),
                ('result', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='guess',
            name='game_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guess',
            name='guess_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guess',
            name='nums_right',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guess',
            name='places_right',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guess',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
