# Generated by Django 2.2.6 on 2020-01-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind_game', '0003_auto_20200129_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='difficulty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='guess',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
