# Generated by Django 2.2.6 on 2020-02-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind_game', '0004_auto_20200129_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='too_high',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guess',
            name='too_low',
            field=models.IntegerField(default=0),
        ),
    ]
