# Generated by Django 2.2.6 on 2020-02-12 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind_game', '0005_auto_20200211_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guess',
            name='too_high',
        ),
        migrations.RemoveField(
            model_name='guess',
            name='too_low',
        ),
    ]
