# Generated by Django 2.2.6 on 2020-02-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind_game', '0006_auto_20200211_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('total_wins', models.IntegerField(default=0)),
                ('total_games', models.IntegerField(default=0)),
                ('average_guesses', models.IntegerField(default=0)),
            ],
        ),
    ]
