# Generated by Django 2.2.6 on 2020-02-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind_game', '0007_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='username',
            field=models.CharField(default='user', max_length=25),
        ),
    ]
